

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default function witAuthlayout({ children }) {
    return (
        <html lang="en">
        <body >
        <h2>layout de (auth)</h2>
        {children}

        </body>

        </html>
    )
}