//import { Inter } from 'next/font/google'
//import './globals.css'


//const inter = Inter({ subsets: ['greek'] })

/*export const metadata = {  quand le titre est un string
    title: 'Create Next App',
    description: 'Generated by create next app',
}*/
export const metadata = { //quand le titre est un objet
    title: {
        absolute:"",//ca fixe le titre et ignore le template
        default:"Next.js Tuto",//c'est le titre par defaut pour les pages que je n'ai pas mis de titre
        template:"%s | edenTUTO"//agis en tant que template
    }
}
export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body /*className={inter.className}*/>
        <h1>bienvenue sur l'appli</h1>
        {children}

        <footer>footer de la layout principale </footer>
        </body>

        </html>
    )
}
//