//import { Inter } from 'next/font/google'
//import './globals.css'

//const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
function getRandomInt(count)
{
    return Math.floor(Math.random()*count);
}


export default function RootLayout({ children }) {
    const ramdon= getRandomInt(2);
    if (ramdon===1)
    {
        throw new Error("Error loading review product id");
    }
    return (
        <html lang="en">
        <body>
        {children}
           <p>layout du dossier products[id]</p>
        </body>

        </html>
    )
}
// className={inter.className}>{children}


